# -*- coding: utf-8 -*-
"""Dogs and Cats Classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wO9L8Kn5uUjGMscoMJT857Zffy6cVKGS
"""

!pip install -Uqq fastai

pip install gradio

#|export
from fastai.vision.all import *
import gradio as gr

def is_cat(x): return x[0].isupper()

im = PILImage.create('dog.jpg')
im.thumbnail((192,192))
im

#|export
learn = load_learner('model.pkl')

learn.predict(im)

#|export
categories = ('Dog','Cat')

def classify_images(img):
  pred,idx,probs = learn.predict(img)
  return dict(zip(categories, map(float,probs)))

classify_images(im)

#|export
image = gr.inputs.Image(shape=(192,192))
label = gr.outputs.Label()

intf = gr.Interface(fn=classify_images, inputs=image, outputs=label)
intf.launch(inline=False)

m = learn.model

ps = list(m.parameters())

ps[1]

ps[0].shape

ps[0]

pip install nbdev